### ISSUE TITLE
How to vizualise Workflows streaming events / agent reasoning?

### ISSUE THREAD

**Issue by notintricate** [run-llama/chat-ui#38]
Hi, what is the proper way of using chat-ui with llama-index workflows?

I'm struggling to properly output streaming events from workflow to ui. 
Vercel useChat streaming is confusing. I want to visualize some form of reasoning like chainlit. 
So i'd like to stream events as the workflow executes with all tool-calling and results, and ultimately output the final message. 

Any hints or examples are highly appreciated!

**Comment by marcusschiesser** [comment]
Have you tried using create-llama to generate some workflow code? It's using a streaming implementation for workflows, just try:

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/974caf0a-0c40-450e-9971-eb68a8c20e39">

**Comment by notintricate** [comment]
Thank you, it helped!
